  services:
    php:
        image: dunglas/frankenphp
        build:
            context: ./docker/production
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        environment:
            EDITOR: '${EDITOR:-nano}'
        volumes:
            - ./:/app
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - blog
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'blog-mariadb:/var/lib/mysql'
        networks:
            - blog
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
networks:
    blog:
        driver: bridge
volumes:
    blog-mariadb:
        driver: local
    caddy_data:
    caddy_config:
