services:
  php:
    image: blog:alpine
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - blog
    depends_on:
      - mariadb
  mariadb:
    image: 'mariadb:latest'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'blog_mariadb:/var/lib/mysql'
    networks:
      - blog
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      retries: 3
      timeout: 5s

networks:
  blog:
    driver: bridge
volumes:
  blog_mariadb:
    driver: local
  caddy_data:
  caddy_config:
